### ISSUE TITLE
No longer correctly orders products

### ISSUE THREAD

**Issue by TriJoe** [Pezmc/TescoSortByPricePerUnit#11]
For example: https://www.tesco.com/groceries/en-GB/search?query=antibacterial%20spray

When clicking enabling the extension, it appears to do some reordering but it's wrong. It results in the following orders of items. None are on special offer.

1. £2.00 _£2.86/litre_
2. £1.50 _£21.43/litre_
3. £2.99 _£5.98/litre_
4. £3.00 _£6.00/litre_ 
5. £2.00 _£2.00/litre_

**Comment by Pezmc** [comment]
Should be fixed as of [v0.0.5](https://github.com/Pezmc/TescoSortByPricePerUnit/releases/tag/v0.0.5), please try it out!
