### ISSUE TITLE
format recognition

### ISSUE THREAD

**Issue by deicidiumx** [Pezmc/TescoSortByPricePerUnit#12]
doesnt seem to place things with the format millilitres or dry weight correctly e.g.

£0.10/100ml 
or 
£5.60/100g DR.WT

**Comment by Pezmc** [comment]
Would you be able to grab the HTML or a page with those results? (Or just link it.) Will try to reproduce.

**Comment by deicidiumx** [comment]
https://www.tesco.com/groceries/en-GB/search?query=seafood

it has 2.23/100g dr wt first, £0.44/100g in the middle of the page, and £0.44/100ml at the bottom of the page

**Comment by Pezmc** [comment]
Fixed in 4673089ef689f4c17ce412134b991296dea7ecac, v0.0.6 released to chrome store, but it may take a few days to be reviewed.
